### ISSUE TITLE
adding a search box would improve the functionality

### ISSUE THREAD

**Issue by trappedinspacetime** [SubwayDesktop/subway-launcher#2]
First of all congratrulations on your innovative project. I happened to come across your `launcher` while looking for a `metro` style linux launcher. I am running Ubuntu 16.04 32 bit in an old laptop, `subway launcher` works well on it. 

I also looked for  `nwjs` projects for a `html` based launchers but I found nothing that kind. 
I am surprised to see that you managed to make `UI` with `html` and `js` without requiring `node`, `nwjs`, `electron` as an alternative approach to them. 

I really appreciate your innovative approach, I hope your project gets known by programmers and become popular.
I wish you continue your project.
Regards.
Kenn

**Comment by 910JQK** [comment]
Sorry for bad English.

I am very glad to hear that someone has interest in my project, although an obsoleted project.
I'll be busy in next several years and my collaborators also have to do a lot of other things, so the whole project won't continue.
But today when I saw your issues, I was moved, because I had never thought this project, which was obsoleted 2 years ago, could be appreciated by someone. So I added a search box and fixed some bugs.

As you are interested in my project, I can tell you more about this project, including Cubway. But it has been midnight in China now so I am going to talk with you tomorrow.

Thanks.

**Comment by trappedinspacetime** [comment]
@910JQK thank you for responding to my issue. I am sorry that I keep you busy. I just tried your quick fix for search box. I liked the style, it's not functional yet but  I don't want to take your time. 
I liked your project because it's the first in its kind. I am using it as my primary application launcher from now on.
As for your English, don't worry about it, you express yourself well. I am also not a native English speaker.
I wish you good luck in your life.
Regards.

**Comment by 910JQK** [comment]
I've replied you at the issuse of Cubway. A search box has been added, so I'll close this issue.
